name: Github Release Workflow
on: [workflow_dispatch]
jobs:
  deploy:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
            java-version: 11
            distribution: 'adopt'
      - name: Download JDK 11
        run: .github/workflows/scripts/downloadJDK.sh
        env:
          OS: ${{ matrix.os }}
      - name: Build Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: mvn --batch-mode clean package -P build-linux
      - name: Build Windows
        if: startsWith(matrix.os, 'windows')
        run: mvn --batch-mode clean package -P build-windows
      - name: Build Windows
        if: startsWith(matrix.os, 'macos')
        run: mvn --batch-mode clean package -P build-macos
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            target/*rodain-app-*
          retention-days: 1